name: GitHub Pages

on:
  push:
    branches:
      - docs

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install MdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.3.7'
      - run: mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: hopdb.dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./book
